# Simple HTML schedule generator
template: "template.html.erb"
url: "http://flash.locamoda.com/fuji/wiffiti/wiffiti-4.7.2.swf"
params: &defaults
    show_title: 0

schedule:
  - name: restaurant
    params:
        id: 30702
    duration: 300

  - name: stadium
    params:
        id: 30703
    duration: 300

  - name: wedding
    params:
        id: 30705
    duration: 300

  - name: retail
    params:
        id: 30706
    duration: 300

