schedule:

  - name: geckboard
    url: "https://boundless.geckoboard.com/dashboard/EA78B0D7BEC6D0DF/"
    duration: 10

  - name: pingdom
    url: "http://stats.pingdom.com/2vgn028rdky6"
    duration: 10

  - name: newrelic
    url: "https://rpm.newrelic.com/public/charts/lpVPUGjY4Wh"
    duration: 10

